### ISSUE TITLE
ISO Cannot Be Opened With ISO Tools

### ISSUE THREAD

**Issue by wagrenier** [wagrenier/ZeroUndub#10]
ISO cannot be opened by any ISO tools because the ISO is not a multiple of `0x800`

Thanks to `neoXite` for finding it.

**Comment by retroNUC** [comment]
This also prevents the ISO (and Zero2Undub) from being compressed with tools like chdman:

```
chdman - MAME Compressed Hunks of Data (CHD) manager 0.239 (mame0239)
ERROR: Unrecognized track type
Error parsing input file (undub.iso: Unsupported format)
Fatal error occurred: 1
```

**Comment by retroNUC** [comment]
Ah, just noticed that this is resolved and works on latest code if I compile myself, just needs a binary release.

**Comment by wagrenier** [comment]
Let me know if it works correctly, I tried it and it worked well. Yes I need to publish a new version but I want to fix other things before. I unfortunately lack time to do so :/

**Comment by IceLancerSR** [comment]
> Let me know if it works correctly, I tried it and it worked well. Yes I need to publish a new version but I want to fix other things before. I unfortunately lack time to do so :/

Hello!
Just compiled your latest patch and used it to make new undub iso. It converts without issues with Chdman now. 
Thanks!

**Comment by wagrenier** [comment]
I have deployed a new version [1.0.3](https://github.com/wagrenier/ZeroUndub/releases/tag/1.0.3)
