### ISSUE TITLE
ZeroUndub fails with message: "Source array not long enough"

### ISSUE THREAD

**Issue by emettkwarren** [wagrenier/ZeroUndub#14]
Could very well be a mistake on my part, but ZeroUndub keeps failing whenever I use it with any of the boxes checked. It creates a "pz_redux" file but after loading it in pcsx2 it doesn't show the credit splash screen, and after selecting 60hz and starting a new game, it crashes/hangs with a black screen. 

![image](https://github.com/wagrenier/ZeroUndub/assets/67929092/28594b7e-4bc6-4ee6-aece-0bbecd9b0783)

It works fine when I don't tick any of the boxes, it shows the 60hz reminder message and when I open it in emulator it shows the credit screen. But this doesn't work because I want the Japanese audio and models and English subs! Thanks for any help.

**Comment by wagrenier** [comment]
Make sure you select the right order for the ISO. The file selector window should tell you in the upper left/right. Otherwise your ISO might not be fully valid

**Comment by emettkwarren** [comment]
I selected it in the right order. Maybe I'm not using the right ROMs? They're titled "Fatal Frame (Asia)" and "Project Zero (Europe)". Is there a specific Japanese copy? or does the Asia one work? Thank you for your help!

**Comment by wagrenier** [comment]
You need the japanese version of the ISO for this to work. I have never tried with the Asia version

**Comment by emettkwarren** [comment]
Ah, that must be the issue. Thanks for the help,

**Comment by wagrenier** [comment]
Let me know if this worked correctly, otherwise there might be an issue.
