### ISSUE TITLE
Errant "205" appears in prologue

### ISSUE THREAD

**Issue by TiredTeddybear** [wagrenier/ZeroUndub#2]
It goes too quickly for me to get a screenshot, but in the prologue after killing the first ghost, Mafuyu says:

"I remember the incident from which I learned from its unique power to capture ghosts."

For a split second, "205" appears onscreen after that. I think this could be easily fixed by just changing "205" to " ".

**Comment by TheRicks94** [comment]
Don't worry. That's part of my clean up job. Stuff like that will show up once in a while.

**Comment by wagrenier** [comment]
Fixed with [b3374ea](https://github.com/wagrenier/ZeroUndub/commit/b3374ea3f1ce0f969add4770130350079db54d9c)
