### ISSUE TITLE
Exclamation mark doesn't show in subtitles

### ISSUE THREAD

**Issue by TiredTeddybear** [wagrenier/ZeroUndub#3]
I don't have a screenshot on hand, but exclamation marks appear as spaces. You can see it toward the end of the intro chapter when Mafuyu cries, "Miku!" (ID 19). Or when Miku is following Koji's ghost, and he says "That woman! That woman in a kimono's coming!" (ID 209)

I am reporting this from playing it on my PS3, for the record.

Edit - The same goes for colons. Not present.

A few more problems

- ID 160 spells "September" as "Septermber" ("Septermber 9th, 9:40 P.M.")
- This subtitle goes outside the game window boundary (ID161)
![image](https://user-images.githubusercontent.com/47927523/130331578-504d811a-30a1-41ab-976f-4869055e7c09.png)

**Comment by TheRicks94** [comment]
It's being worked on. I've mentioned it to Dev the other night.

**Comment by wagrenier** [comment]
Thanks for the feedback! "!" was not among the character list, next push will fix fix that.

**Comment by wagrenier** [comment]
For the tape subtitle, I have created a different issue as it is different from the one described in the title.

**Comment by wagrenier** [comment]
Fixed with [b3374ea](https://github.com/wagrenier/ZeroUndub/commit/b3374ea3f1ce0f969add4770130350079db54d9c)
