### ISSUE TITLE
patcher is confusing.

### ISSUE THREAD

**Issue by RetroGameTalk** [wagrenier/ZeroUndub#5]
Hello, i want to say the patcher is not intuitive. And there are not instructions anywhere either.

There are 3 checkboxes: Import subtitles, Undub, Import 3D models.
What do they do exactly? If i select neither what does the patch do? Nothing?

It asks you to "Select files" It doesn't state which files. By instructions it's supposed to be the JP and EU isos.
In what order? Does it matter?

After you do that a message says "Copying the US iso" 
What does it even mean? What US iso? (Up to this point no US iso was involved in any part of the process).

Then it says completed.
What did it do? Did it patch an iso? Which one? The JP? The EU? did it create a new one? Where is it?

**Comment by wagrenier** [comment]
Hi, 

Thank you for the report. The file selector does state which file to select in the upper left window. 

The US Iso is a mistake left from FF2 patcher, so I'll fix that. I'll also add a dialogue box warning which file to select.

For the copying iso, like it says, it is making a copy of your original iso so if anything happens, your file will not be corrupted. The undub version is pz_.... and is located in the same folder as the eu iso.

When it says done, it means the patching is completed, and the options you selected were injected into the game.

**Comment by wagrenier** [comment]
Fixed with commit [e393d23](https://github.com/wagrenier/ZeroUndub/commit/e393d2310dce26feeab99def3cd21cc52e8b00f0)

**Comment by RetroGameTalk** [comment]
Thanks, sorry for being obnoxious.

**Comment by RetroGameTalk** [comment]
I gave it another go. This is what i do:

1) Open program.
2) Select "Undub" checkbox
3) Click "Select files"
4) Choose EU iso
5) Choose JP iso
6) CLick "Undub" button.
7) Wait.
8) Message says it's done it.
9) Find pz_redux.iso
10) Open pz_redux.iso with PCSX2.
11) Start a new game.
12) Voices are in English.

Is there something i'm doing wrong?

**Comment by wagrenier** [comment]
You did not put the game in 60Hz, in game voices are in Japanese. I'll add a message about that

**Comment by RetroGameTalk** [comment]
That was it.
I just suck at this.
