### ISSUE TITLE
Grammar error reports

### ISSUE THREAD

**Issue by TiredTeddybear** [wagrenier/ZeroUndub#6]
I went through the latest Transcribe.JSON and found a few remaining issues.

ID 78: "They're exactly the same as the ones mom took." -> "They're exactly the same as the ones Mom took."

capitalized first m of Mom b/c she's referring to her as a name

ID 122: "Her soul must remain here keeping this gate sealed off for all eternity" -> "Her soul must remain here, keeping this gate sealed off for all eternity"

added comma between "here" and "keeping" to avoid run-on sentence

ID 160: "Septermber 9th, 9:40 P.M." -> "September 9th, 9:40 P.M."

fixed typo of September

ID 226: "Beyond this door, the mirror must be there.." -> "Beyond this door, the mirror must be there..."

added missing period to ellipsis

**Comment by wagrenier** [comment]
Fixed with version [86d04c9](https://github.com/wagrenier/ZeroUndub/commit/86d04c924cb02a5c4920dce9cd051ea26f51c15e)
