### ISSUE TITLE
1.0.2 subtitle bug in PCSX2

### ISSUE THREAD

**Issue by hibiol** [wagrenier/ZeroUndub#8]
no original hardware to test this on so i apologize if this is troublesome/not supported; after running the patcher (and checking all 3 boxes) the subtitles are left in this strange state:
![pcsx2_BcuQi9Y9Jr](https://user-images.githubusercontent.com/86580370/132972610-7537f92b-8329-4cce-b3f8-3946afabad03.png)
for reference i'm playing in english/60hz modes. i've tried the FF2 undub and that works perfectly, so i'm unsure what's up here. thanks in advance for taking a look at this!

**Comment by wagrenier** [comment]
What version of the undubber did you use? It seems like you have used a dev build/early build of the patcher. Use [version 1.0.2](https://github.com/wagrenier/ZeroUndub/releases/tag/1.0.2) for the latest patch. Also, the game was tested for both real hardware and PCSX2!

**Comment by hibiol** [comment]
ah yeah, it was 1.0.2 that i used. i tried applying it twice more and was able to replicate it again, i'll see about re-ripping my discs in the event something went wrong there.

**Comment by wagrenier** [comment]
Can you try version 1.0.1? I have made changes with how the file is being written and it could be issue. However when I tried it I worked properly.

**Comment by hibiol** [comment]
sure thing! 1.0.1 seems to work just fine for me:
![pcsx2_rk3PTxBwP1](https://user-images.githubusercontent.com/86580370/132973705-dfd0b462-a52f-4728-8714-64b5781dd029.png)

**Comment by wagrenier** [comment]
Strange, I'll fix everything tomorrow, v1.0.1 is a 95% undub, so this shouldn't be an issue for today

**Comment by hibiol** [comment]
no rush at all, thank you very much!

**Comment by wagrenier** [comment]
Can you check what is inside the transcribe.json file for the 1.0.2 version?

**Comment by wagrenier** [comment]
Patcher has been updated, redownload v1.0.2 and let me know if it works.

**Comment by hibiol** [comment]
works perfectly, thank you!
